### ISSUE TITLE
keybindings not working

### ISSUE THREAD

**Issue by minyez** [publicimageltd/delve#1]
Hi!

I happened to get here, when I tried to search for solutions to some sqlite error thrown by dashboard after some roam updates. I can't wait to give it a try as soon after seeing the screenshot with nicely formatted tags. Thanks for extending org-roam-dashboard by developing delve! 

After installing both delve and list, I managed to get to the delve-mode with a view similar to your screenshot (see below). I can navigate among lists by usual navigation keys, but fail to use TAB to expand the list or ENTER to go to the Zettel. The function works, as `M-x delve-expand-toggle-sublist` opens the list.

![7551604932104_ pic_hd](https://user-images.githubusercontent.com/25758395/98554170-63a6f380-22db-11eb-811c-11e9273d93d1.jpg)

My configuration of Doom Emacs `config.el`

```lisp
(use-package lister)
(use-package delve
  :config
  (use-package delve-minor-mode
    :config
    (add-hook 'org-mode-hook #'delve-minor-mode-maybe-activate)
  )
  :bind
  (("<f12>" . delve-open-or-select))
)
```

Versions: Emacs 27.1 (Doom v2.0.9)

**Comment by publicimageltd** [comment]
Thanks for trying! I have no clue why the keybindings won't work. I guess it has something to do with finding the right value to map the function. Try the following: In delve-mode, press your tab key. Then type `C-h l` to see what key event is listed there. In my case, I see "<tab>". What do you see? Same with enter.

**Comment by minyez** [comment]
Thanks for the reply. I followed your instructions and got the information

```lisp
<tab>                  ;; better-jumper-jump-forward
<return>               ;; evil-ret
```

Are they supposed to be `;;delve-expand-toggle-sublist` and `;;delve-visit-zettel`?

**Comment by publicimageltd** [comment]
You name it. It should be `delve-expand-toggle-sublist` and `lister-key-action`. So the keymap is not bound. But your major mode is `delve-mode`, right? Check this with pressing `C-M-:` (or `M-x eval-expression`) and then enter `major-mode` in the prompt. It should return `delve-mode`.

You seem to use evil, which I do not use. So maybe evil is interfering. Maybe you could try and turn evil off and check if that causes the problem.

**Comment by minyez** [comment]
`major-mode` is indeed `delve-mode`.
After turning off evil (`M-x evil-mode`), everything works like a charm :) So this evil is the culprit.
Do you have any hints on how to turn off evil mode when entering delve, and switch on after leaving it?

**Comment by publicimageltd** [comment]
As I said, I don't use evil. But looking at the docs, I think the following snippet might be worth a try:

```emacs-lisp
(evil-set-initial-state 'delve-mode 'emacs)
```

See, for example, this configuration file, which makes heavy use of this function: 

https://github.com/chrisbarrett/.emacs.d/blob/c496cdbeef855540f0ffad98f42993e34d45e11b/config/config-evil.el#L100

To test it, do not forget to completely kill the delve buffer before reopening it, so that all the mode specific settings can be applied.

Tell me if it worked, so I might add it to the readme.

**Comment by minyez** [comment]
Thank you very much for the help. Adding the snippet to the configuration file solves the problem nicely.

**Comment by publicimageltd** [comment]
I'll update the readme. Feel free to post another issue if there's a problem.

**Comment by oatmealm** [comment]
Hi! Thanks for delve... amazing step forward from the dashboard, which I was still using :) 

About evil and delve, I've got the following in my confg (for Doom) which works so far, though I didn't test all aspects... I think the right/left key on an item doesn't work for me either, though didn't check deeper...

```
(use-package! delve
  :bind (("<f12>" . delve-open-or-select))
  :config
  (set-evil-initial-state! 'delve-mode 'insert)
  (map! :map delve-mode-map
        :n "gr"      #'delve-refresh-buffer
        :n "<right>" #'delve-expand-insert-tolinks
        :n "<left>"  #'devle-expand-insert-backlinks
        :localleader
        "RET"  #'lister-key-action
        "TAB"  #'delve-expand-toggle-sublist)
  (use-package! delve-minor-mode
    :hook (org-roam-mode . delve-minor-mode-maybe-active)))
```

**Comment by publicimageltd** [comment]
Thanks @oatmealm  for posting this snippet! I have opened an enhancement issue for collecting this kind of stuff, so that we could eventually include this into the source code. BTW I have edited your snippet (changing `delve-minor-mode-maybe-active` to `delve-minor-mode-maybe-activate`).

**Comment by oatmealm** [comment]
Thanks for the correction!
