### ISSUE TITLE
"Mandatory ARGLIST is missing"

### ISSUE THREAD

**Issue by DavidFeest** [publicimageltd/delve#17]
Hi, 
when starting delve I get a the error message "Mandatory ARGLIST is missing".

**Comment by DavidFeest** [comment]
I'm using delve 0.9.4 and org-roam 2.2.2, both installed with straight. My configuration is standard as described in the manual:

**Comment by DavidFeest** [comment]
(use-package delve
      :straight (:repo "publicimageltd/delve"
                :host github
                :type git)
      :after (org-roam)
    ;; this is necessary if use-package-always-defer is true
    :demand t
     :bind
    ;; the main entry point, offering a list of all stored collections
    ;; and of all open Delve buffers:
     (("<f11>" . delve))     
     :config
     ;; set meaningful tag names for the dashboard query
    (setq delve-dashboard-tags '("Tag1" "Tag2"))
     ;; optionally turn on compact view as default
     (add-hook #'delve-mode-hook #'delve-compact-view-mode)
    ;; turn on delve-minor-mode when Org Roam file is opened:
     (delve-global-minor-mode))
; one file name -- one directory:
  (setq delve-storage-paths "/home/XXX/org/delve")

**Comment by publicimageltd** [comment]
Thanks for reporting the issue! Did you get the warning when you executed the `use-package` declaration? For it looks like  you do not provide a key binding for `:bind`. Anyways, please turn on `toggle-debug-on-error` (`M-x toggle-debug-on-error`), then paste the result of the buffer with the error here.

**Comment by publicimageltd** [comment]
Ah, that's the issue with the missing `()` in the transient. That should be resolved, please update `Delve` and check again.
