### ISSUE TITLE
ewoc-nth: Wrong type argument: ewoc, nil

### ISSUE THREAD

**Issue by incandescentman** [publicimageltd/delve#18]
New to Delve. When I did delve--key--insert node, I got this error: `ewoc-nth: Wrong type argument: ewoc, nil`

**Comment by publicimageltd** [comment]
Thanks for reporting! Can you give me so e additional context? E.g. was the buffer empty (no items yet added)? Did you call the function interactively?

Am 15. Mai 2023 19:56:24 MESZ schrieb Jay Dixit ***@***.***>:

**Comment by publicimageltd** [comment]
Closing the issue due to inactivity
