### ISSUE TITLE
Is it possible to update the DELVE DASHBOARD without closing and opening again?

### ISSUE THREAD

**Issue by akashpal-21** [publicimageltd/delve#20]
Suppose I create a new node after the DELVE DASHBOARD is created, the node doesn't show up in the dashboard, I have to close and reopen it to achieve it... Is there any way to update the dashboard with new nodes/pages without closing it ?

Currently I use this hack function to achieve this : This function will depending where the user is currently, do two things, if the user is on the Delve Dashboard, it will update it - if the user is not on the Dashboard it will simply call the (delve) function which asks the user if they want to visit any collection.

If anyone want to reuse this code, substitute 0 for your buffer name, "DASHBOARD" is the default name.

```
(defun delve-dashboard-update ()
  "Check if 'DELVE 0' buffer is active, close it, and re-execute (delve)."
  (interactive)
  (let ((delve-buffer (get-buffer "DELVE 0")))
    (when (and delve-buffer (get-buffer-window delve-buffer t))
      (kill-buffer delve-buffer))
    (call-interactively #'delve)))

(with-eval-after-load 'delve
  (define-key delve-mode-map (kbd "G") #'delve-dashboard-update))       ; update (close&reopen) Delve Dashboard 

```

My delve-dashboard-name is "0"

**Comment by publicimageltd** [comment]
I have changed the behavior of "update" (g). If queries are open, new Zettels are automatically inserted in the indented tree belonging to the query. I hope it works satisfactorily. Please have a look and then close this issue.

**Comment by publicimageltd** [comment]
Ah I see, I forgot to test that direction of sync. So I'll add that next, that's a good idea.

**Comment by publicimageltd** [comment]
Two-way sync is set up. Have fun!

**Comment by publicimageltd** [comment]
I can't replicate the problem. Please use the test environment which can be started with `bin/test-emacs` from the repo's root directory to reprduce it. I just did the following in the test environment and had no error, maybe I misunderstood you:

 - I went to the first node in the list "last modified" (CTRL-ENTER)
 - I added a node at the end of that file (new heading, `org-store-link`, write file)
 - I went back to the Dashboard buffer. I press `g`, and the new node shows up.
 - I go back to the buffer and delete the new node manually (the text in the buffer including the heading).
 - I save the file again
 - I go back to dashboard and press `g`. The new node disappears.

**Comment by publicimageltd** [comment]
Ah, I just found the bug. It can be reproduced when you delete the whole file, instead of just a node in a file (what I did). I'll have a look. Great bug hunting! :-)
